### Get all blogs
GET http://localhost:3003/api/blogs

### Create new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5OWEwZDYxYjIzYmE4OWVkNTU3Mzc5ZiIsImlhdCI6MTc3MTg3Mzk3MX0.BKfW1Kd87EKaQ6WcS5rF315EjZyfPRmNLwX48gi5D6E

{
  "title": "Eighth",
  "author": "mustafa",
  "url": "example-blog.com",
  "likes": 10
}

### Delete blog
DELETE http://localhost:3003/api/blogs/6992fd67b138c70af739f42a

### Update blog
PUT http://localhost:3003/api/blogs/69871141ab3154cfb07a9c6f
Content-Type: application/json

{
    "title": "sixth",
    "author": "mustafa",
    "url": "example-blog.com",
    "likes": 40,
    "id": "69871141ab3154cfb07a9c6f"
}