### Get all blogs
GET http://localhost:3003/api/blogs

### Create new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "sixth",
  "author": "mustafa",
  "url": "example-blog.com",
  "likes": 4
}