### Get users
GET http://localhost:3003/api/users

### Create a user
POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "mstf",
  "name": "mustafa",
  "password": "fullStack26"
}